# Generated by Django 2.0.2 on 2018-03-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat', models.TextField(blank=True, null=True)),
                ('nome', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
