# Generated by Django 2.0.2 on 2018-03-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Notas_mat',
        ),
    ]
